version: '3.2'
services:
  p4d.helix:
    build:
      context: helix-p4d
      dockerfile: Dockerfile
    hostname: p4d
    domainname: helix
    ports:
      - 4000:1666
    volumes:
      - ./volumes/p4d-home:/p4
      - ./volumes/p4-ssl:/p4-ssl
    environment:
      - P4SSLDIR=/p4-ssl
    tty: true

  build.helix:
    build:
      context: helix-build
      dockerfile: Dockerfile
    hostname: build
    domainname: helix
    ports:
      - 4001:1666
    depends_on:
      - p4d.helix
    volumes:
      - ./volumes/p4-ssl:/p4-ssl
    environment:
      - P4SSLDIR=/p4-ssl
    tty: true

  swarm.helix:
    build:
      context: helix-swarm
      dockerfile: Dockerfile
    hostname: swarm
    domainname: helix
    ports:
      - 5080:80
    depends_on:
      - build.helix
    volumes:
      - ./volumes/p4-ssl:/p4-ssl
    environment:
      - P4SSLDIR=/p4-ssl
    tty: true

  # search.helix:
  #   build:
  #     context: p4-search
  #     dockerfile: Dockerfile
  #   hostname: search
  #   domainname: helix
  #   ports:
  #     - 4088:8088
  #     - 8983:8983
  #   depends_on:
  #     - p4d.helix
  #   volumes:
  #     - ./volumes/p4-ssl:/p4-ssl4
  #   environment:
  #     - P4SSLDIR=/p4-ssl
  #   tty: true